apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-mf4d
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-mf4d
    app.kubernetes.io/part-of: tkrw-pr712-0075-0050-app
  name: devfile-sample-mf4d
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-mf4d
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-mf4d
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0050-tenant/tkrw-pr712-0075-0050-app/devfile-sample-mf4d@sha256:b39dbad51f519ff78bb8fd5c462bea134b4e36a38d01312a5a23a69c477bc51c
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
